# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeTest' do
  pod 'AppCenter/Crashes', '~> 1.13.0'
  pod 'AppCenter/Analytics', '~> 1.13.0'
  pod 'AppCenterReactNativeShared', '~> 1.12.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeTest

  

  platform :ios, '9.0'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'ReactNativeTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeTest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeTest-tvOS

  target 'ReactNativeTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
